import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import "../globals.css";
import Sideuser from "@/components/Sidebar/Sideruser";
import Footer from "@/components/Footer/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function usuarioLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <Sideuser/>
        {children}
       <Footer/>

        
      </body>
    </html>
  );
}
